### ISSUE TITLE
[Bug] File browser not working

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#8]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

chromeOS , 117 stable

### The device you're connecting to

samsung galaxy A53 5G

### What did you do and what happened?

i connected my device, went to file browser, and it didn't work

### (Optional) Browser console output

```Text
(8) Connect failed
```

**Comment by CorruptionVR** [comment]
same also happens on windows

**Comment by yume-chan** [comment]
Does your device have a microSD card installed? 

> and it didn't work

What did it show? Are there any error messages?

Can you use the version at https://debug.tangoapp.dev/ , connect to your device, open file browser, and copy-paste all output in browser DevTools here?

**Comment by CorruptionVR** [comment]
> Does your device have a microSD card installed?

yes

> What did it show? Are there any error messages?

if you mean as in popup elements like when the device disconnects, no

> Can you use the version at https://debug.tangoapp.dev/ , connect to your device, open file browser, and copy-paste all output in browser DevTools here?

```console
Connect failed
Started
Listening
command: 1
storageVolumes:

java.lang.SecurityException: callingPackage does not match UID
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.os.storage.IStorageManager$Stub$Proxy.getVolumeList(IStorageManager.java:2241)
	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:1498)
	at android.os.storage.StorageManager.getStorageVolumes(StorageManager.java:1401)

	at moe.chensi.tango.Worker.listVolumes(Worker.kt:108)
	at moe.chensi.tango.Worker.main$lambda$1(Worker.kt:66)
	at moe.chensi.tango.Worker.$r8$lambda$JTttrc2BqNKmr0fLtjVA-ebe_o8(Unknown Source:0)
	at moe.chensi.tango.Worker$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.StorageManagerService.getVolumeList(StorageManagerService.java:4409)
	at android.os.storage.IStorageManager$Stub.onTransact(IStorageManager.java:1101)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)


```

I am using Eruda to view the console because my school has blocked inspect.

**Comment by CorruptionVR** [comment]
I just tested it with the old demo, and it still works on there

**Comment by yume-chan** [comment]
I found the issue on Android 13.

> I just tested it with the old demo, and it still works on there

The new app uses Android API to retrieve storage volumes like "Internal Storage" or "SD Card". The old demo starts at filesystem root (`/`).

**Comment by CorruptionVR** [comment]
wait, so does android 13 not have that API?

**Comment by yume-chan** [comment]
There was a race condition in my code. In fact, it works when refresh button is clicked. It has been fixed now.

**Comment by CorruptionVR** [comment]
oh, ok
also, how long does it usually take for the site to update?
edit: nevermind, apparently it updates really quickly.
